# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
